air:
  adapter: wlan0

  bindPhrase: lv-air
  frequency: 5500

  # Comment out when using setup with repeater
  # bindPhrase: lv-link-repeater

  width: 20
  txPower: 35
  mcs: 1
  silent: false

router:
  io:
    - name: video
      endpoint:
        type: udp_server
        ip: 127.0.0.1
        port: 5600
        mtu: 1440

    - name: tunnel
      endpoint:
        type: tun
        adapter: lvlink0
        ip: 192.168.27.2
        mtu: 1440

    - name: rc
      protocol: crsf
      endpoint:
        type: uart
        path: /dev/ttyAMA1
        baud: 420000
        mtu: 26

    - name: mavlink
      endpoint:
        type: udp_server
        ip: 127.0.0.1
        port: 27010
        mtu: 500

  pipes:
    - id: 0
      fec: 70
      blockSize: 8
      forceSendAfter: 50 # ms
      io: video

    - id: 1
      fec: 0
      io: tunnel

    - id: 2
      fec: 0
      io: rc

    - id: 3
      fec: 50
      io: mavlink

mavlink:
  enabled: true

  endpoint:
    type: udp_server
    ip: 127.0.0.1
    port: 14540
    mtu: 280

  # uart endpoint is supported too
  # endpoint:
  #   type: uart
  #   path: /dev/ttyAMA0
  #   baud: 57600
  #   mtu: 280

  telemetry:
    enabled: true
    # in seconds
    updatePeriod: 5

rc:
  frequency:
    enabled: true

    channel: 13
    mapping:
      5320 : [800,990]
      5180 : [991,1071]
      5540 : [1072,1152]
      5500 : [1153,1233]
      5600 : [1234,1314]
      5680 : [1315,1395]
      5720 : [1396,1476]
      5785 : [1477,1557]
      5805 : [1558,1638]
      5845 : [1639,1719]
      5905 : [1720,1800]
      5945 : [1801,1881]
      6005 : [1882,2001]

  silentMode:
    enabled: false

    channel: 13
    mapping:
      0 : [800,2001]
      1 : [2002,2200]

  txPower:
    enabled: true

    channel: 14
    mapping:
      1 : [800,1000]
      35 : [1000,2200]

  mcs:
    enabled: false
    channel: 10
    mapping:
      0: [800, 1200]
      1: [1200, 1500]
      2: [1500, 2100]

  pipes:
    - id: 0
      fec:
        enabled: true
        channel: 14
        mapping:
          10: [ 800, 1000]
          20: [1000, 1100]
          40: [1100, 1200]
          60: [1200, 1300]
          80: [1300, 1400]
          90: [1400, 1500]
          100: [1500, 1600]
          120: [1600, 1700]
          140: [1700, 1800]
          160: [1800, 2200]
